# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 311, 321))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEditLocalHostName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditLocalHostName.setGeometry(QtCore.QRect(90, 30, 201, 21))
        self.lineEditLocalHostName.setObjectName("lineEditLocalHostName")
        self.edtRecv = QtWidgets.QTextEdit(self.groupBox)
        self.edtRecv.setGeometry(QtCore.QRect(90, 160, 201, 101))
        self.edtRecv.setObjectName("edtRecv")
        self.btnConnect = QtWidgets.QPushButton(self.groupBox)
        self.btnConnect.setGeometry(QtCore.QRect(120, 280, 61, 28))
        self.btnConnect.setObjectName("btnConnect")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 280, 71, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEditAddress = QtWidgets.QTextEdit(self.groupBox)
        self.textEditAddress.setGeometry(QtCore.QRect(90, 90, 201, 41))
        self.textEditAddress.setObjectName("textEditAddress")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 10, 311, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 72, 15))
        self.label_4.setObjectName("label_4")
        self.edtIP = QtWidgets.QLineEdit(self.groupBox_2)
        self.edtIP.setGeometry(QtCore.QRect(110, 40, 161, 21))
        self.edtIP.setObjectName("edtIP")
        self.edtPort = QtWidgets.QLineEdit(self.groupBox_2)
        self.edtPort.setGeometry(QtCore.QRect(110, 100, 161, 21))
        self.edtPort.setObjectName("edtPort")
        self.edtSend = QtWidgets.QTextEdit(self.groupBox_2)
        self.edtSend.setGeometry(QtCore.QRect(50, 150, 221, 121))
        self.edtSend.setObjectName("edtSend")
        self.btnSend = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSend.setGeometry(QtCore.QRect(130, 280, 61, 28))
        self.btnSend.setObjectName("btnSend")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 280, 71, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "详细信息"))
        self.label.setText(_translate("MainWindow", "主机名:"))
        self.label_2.setText(_translate("MainWindow", "地址:"))
        self.btnConnect.setText(_translate("MainWindow", "连接"))
        self.pushButton_2.setText(_translate("MainWindow", "查询网络"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_3.setText(_translate("MainWindow", "IP"))
        self.label_4.setText(_translate("MainWindow", "PORT"))
        self.edtIP.setText(_translate("MainWindow", "10.205.253.65"))
        self.edtPort.setText(_translate("MainWindow", "9988"))
        self.btnSend.setText(_translate("MainWindow", "发送"))
        self.pushButton_4.setText(_translate("MainWindow", "退出"))
